apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  app: nginx
spec:
 replicas: "{{ .values.deployment.replicasCount }}"
 selector:
  matchLabels:
   app: nginx 
   project: roboshop
   component: frontend
 template:
  metadata:
   labels:
    app: nginx 
    project: roboshop
    component: frontend
  spec:
   containers:
    - name: nginx
      image: "nginx:{{ .values.deployment.imageVersion }}"
      ports:
       - name: http-web-svc
         containerPort: 80